services:
  redis-node-1:
    image: redis:8.0.2
    container_name: redis-node-1
    ports:
      - "7001:7001"
      - "17001:17001"
    command: redis-server /etc/redis/redis.conf --port 7001 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7001:/etc/redis
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:8.0.2
    container_name: redis-node-2
    ports:
      - "7002:7002"
      - "17002:17002"
    command: redis-server /etc/redis/redis.conf --port 7002 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7002:/etc/redis
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:8.0.2
    container_name: redis-node-3
    ports:
      - "7003:7003"
      - "17003:17003"
    command: redis-server /etc/redis/redis.conf --port 7003 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7003:/etc/redis
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:8.0.2
    container_name: redis-node-4
    ports:
      - "7004:7004"
      - "17004:17004"
    command: redis-server /etc/redis/redis.conf --port 7004 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7004:/etc/redis
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:8.0.2
    container_name: redis-node-5
    ports:
      - "7005:7005"
      - "17005:17005"
    command: redis-server /etc/redis/redis.conf --port 7005 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7005:/etc/redis
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:8.0.2
    container_name: redis-node-6
    ports:
      - "7006:7006"
      - "17006:17006"
    command: redis-server /etc/redis/redis.conf --port 7006 --cluster-announce-ip ${DOCKER_HOST_IP}
    volumes:
      - ./RedisCluster/7006:/etc/redis
    networks:
      - redis-cluster

# Executes command to create the cluster
  redis-cluster-create:
    image: redis:8.0.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: >
      sh -c "
        sleep 5;
        echo yes | redis-cli --cluster create ${DOCKER_HOST_IP}:7001 ${DOCKER_HOST_IP}:7002 ${DOCKER_HOST_IP}:7003 ${DOCKER_HOST_IP}:7004 ${DOCKER_HOST_IP}:7005 ${DOCKER_HOST_IP}:7006 --cluster-replicas 1"
    networks:
      - redis-cluster

# Web dashboard for redis cluster
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    ports:
      - "5540:5540"
    volumes:
      - ./logs/redisinsight:/data/logs
    environment:
      RI_REDIS_HOST_7001: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7001: 7001
      RI_REDIS_HOST_7002: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7002: 7002
      RI_REDIS_HOST_7003: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7003: 7003
      RI_REDIS_HOST_7004: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7004: 7004
      RI_REDIS_HOST_7005: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7005: 7005
      RI_REDIS_HOST_7006: ${DOCKER_HOST_IP}
      RI_REDIS_PORT_7006: 7006
    networks:
      - redis-cluster

# Cluster entry point
# Use RedisViaHAProxy run configuration to connect through it
  redis-cluster-endpoint:
    # Currently the latest version is 3.2
    image: haproxy:latest
    container_name: redis-cluster-endpoint
    ports:
      - "6379:6379"
    volumes:
      - ./RedisCluster/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    environment:
      FRONTEND_PORT: 6379
      BACKEND_HOST: ${DOCKER_HOST_IP}
      BACKEND_PORT_1: 7001
      BACKEND_PORT_2: 7002
      BACKEND_PORT_3: 7003
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge