##
# Connect to Redis cluster through all nodes
##
redis.cluster.nodes=redis.it:7001,redis.it:7002,redis.it:7003,redis.it:7004,redis.it:7005,redis.it:7006

## Logging configuration
logging.config=config/logback.xml